### ISSUE TITLE
macOS DMG creation fails in Mu's CI

### ISSUE THREAD

**Issue by tmontes** [mu-editor/pup#127]
FACTS:

* A PR has been raised against the Mu repo to integrate `pup` packaging into CI -- https://github.com/mu-editor/mu/pull/1234.
* A few attempts show that the DMG creation stage, based on `dmgbuild`, fail with a `hdiutil: detach: timeout for DiskArbitration expired` message.
* @carlosperate found [this `dmgbuild` issue](https://github.com/al45tair/dmgbuild/issues/26) which seems to identify this precise failure.

Let's see if we can contribute to `dmgbuild`'s improvement, here. :-)

**Comment by tmontes** [comment]
INVESTIGATION:

* Confirmed that the [failing Mu's CI build here](https://github.com/mu-editor/mu/pull/1234/checks?check_run_id=1678294244)...
* ...matches `dmgbuild`'s (kind-of) hardcoded 5 attempts at running `hdiutil detach ...`...
* ...in [`dmgbuild/core.py:606`](https://github.com/al45tair/dmgbuild/blob/master/dmgbuild/core.py#L606)...
* ...with `detach_retries` defined in [`dmgbuild/core.py:158`](https://github.com/al45tair/dmgbuild/blob/master/dmgbuild/core.py#L158) as an optional function parameter...
* ...but never called differenty, at least from the setuptools entrypoint `dmgbuild` CLI command -- https://github.com/al45tair/dmgbuild/blob/master/scripts/dmgbuild.

Seems consistent with `dmgbuild`'s issue identified above. What's not so clear is the timings:

* `dmgbuild` calls `hdiutil detach` up to 5 times, waiting one second between each attempt.
* Mu's CI build log -- happily timestamped by `pup` -- indicate different timings:

```
20210110 232406 I pup.api Step 'mac.create-dmg': starting.
20210110 232632 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: timeout for DiskArbitration expired
20210110 232632 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: drive not detached
20210110 232833 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: timeout for DiskArbitration expired
20210110 232833 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: drive not detached
20210110 233046 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: timeout for DiskArbitration expired
20210110 233046 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: drive not detached
20210110 233247 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: timeout for DiskArbitration expired
20210110 233247 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: drive not detached
20210110 233449 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: timeout for DiskArbitration expired
20210110 233449 I pup.plugins.mac.create_dmg dmgbuild err: hdiutil: detach: drive not detached
20210110 233539 I pup.plugins.mac.create_dmg dmgbuild err: Traceback (most recent call last):
20210110 233539 I pup.plugins.mac.create_dmg dmgbuild err:   File "/Users/runner/work/mu/mu/venv-pup/bin/dmgbuild", line 36, in <module>
20210110 233539 I pup.plugins.mac.create_dmg dmgbuild err:     dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
20210110 233539 I pup.plugins.mac.create_dmg dmgbuild err:   File "/Users/runner/work/mu/mu/venv-pup/lib/python3.7/site-packages/dmgbuild/core.py", line 614, in build_dmg
20210110 233539 I pup.plugins.mac.create_dmg dmgbuild err:     raise DMGError('Unable to detach device cleanly')
20210110 233539 I pup.plugins.mac.create_dmg dmgbuild err: dmgbuild.core.DMGError: Unable to detach device cleanly
20210110 233539 E pup.plugins.mac.create_dmg [Errno 2] No such file or directory: '/Users/runner/work/mu/mu/build/pup/Mu Editor.dmgbuild/Mu Editor 1.1.0a3.dmg'
20210110 233539 I pup.api Step 'mac.create-dmg': completed.
```

**Comment by carlosperate** [comment]
I might not trust the CI timings too much, in some of my other projects with a couple of processes printing to stdout they come completely out of order and somewhat batched, so I wouldn't be surprised if stdout is not flushed that much.

**Comment by tmontes** [comment]
GOOD PROGRESS:

* Hacked Mu Editor's CI to use a a forked `dmgbuild` that retries the `hdiutil detach` for longer.
* This lead to the successful generation of the DMG file on the Mu Editor's CI.

THUS:

* Logged a note on `dmgbuild`'s issue -- https://github.com/al45tair/dmgbuild/issues/26#issuecomment-763126848 -- asking the author if a PR would be accepted.

NEXT:

(keep this open for a while and then)

* If a `dmgbuild` PR and subsequent release comes out:
  * Have `pup` be configurable in such a way that `dmgbuild`'s behaviour in this regard is configurable.
  * Adjust Mu Editor's CI scripts to make use of that.
* Otherwise:
  * At least update `pup`'s docs highlighting such eventual limitation.

**Comment by tmontes** [comment]
(self-note: pinged `dmgbuild`'s maintainer)

**Comment by tmontes** [comment]
SELF-NOTE:

* Updated `dmgbuild` dependency from 1.4.2 to 1.5.2 in #220.
* [This comment](https://github.com/al45tair/dmgbuild/issues/26#issuecomment-851388909) indicates that the issue might be solved in a merged PR back from May 2021.
* Per `dmgbuild`s commit history, 1.5.2 should include that fix.

NEXT:

* Try the updated `dmgbuild` -- to be brought in in the next release of `pup` -- in Mu's CI.

**Comment by tmontes** [comment]
PROGRESS:

* `pup` 1.0.0a17 released, now using the updated `dmgbuild` 1.5.2.
* Let's see how Mu's CI under GitHub actions behaves.
* Created [this Mu PR](https://github.com/mu-editor/mu/pull/2276).

**Comment by tmontes** [comment]
NEXT, if Mu's PR is merged:

* Delete `dmgbuild`'s fork.
* Feedback `dmgbuild`'s maintaners on [this issue](https://github.com/dmgbuild/dmgbuild/issues/26#issuecomment-763126848).

**Comment by tmontes** [comment]
PROGRESS:

* Merged Mu's PR -- all things looking good there.
* Deleted my `dmgbuild` fork repo.
* Added feedback to `dmgbuild`'s issue.

CLOSING
