### ISSUE TITLE
macOS signing failure

### ISSUE THREAD

**Issue by tmontes** [mu-editor/pup#138]
SUMMARY:

* PyPI installed `pup` fails at signing macOS binaries.

MOTIVE:

* The PyPI distribution does not include the `entitlements.plist` resource file.

IRONY:

* A packaging failure in a packaging tool? Why not? :)

**Comment by tmontes** [comment]
Closing after having merged #139.

**Comment by ntoll** [comment]
WFM :-P :tada:
