### ISSUE TITLE
Win MSI | Support both per-machine and per-user installs

### ISSUE THREAD

**Issue by tmontes** [mu-editor/pup#151]
POSSIBLE SCENARIOS:

* No UI, per-machine MSI.
* No UI, per-user MSI.
* No UI, per-machine if current user has such privileges, per-user otherwise.
* Custom UI, with the default being one of the above.

A few links that might help investigating a possible implementation:

* https://stackoverflow.com/questions/5411585/setting-allusers-in-wix-for-per-user-or-per-machine-installation-context
* https://sourceforge.net/p/wix/mailman/message/28378224/
* https://helgeklein.com/blog/2014/09/real-world-example-wix-msi-application-installer/
* https://www.firegiant.com/wix/tutorial/user-interface/
* https://subscription.packtpub.com/book/application_development/9781849513722/1/ch01lvl1sec09/adding-a-user-interface

**Comment by tmontes** [comment]
Linking to Beeware's `briefcase` issue I explored a while back:

* https://github.com/beeware/briefcase/issues/382

In short:

* A user-installable MSI (much like the one produced by `pup`?)  can be machine installed with:
```
C:\...> msiexec /i the-msi-file.msi MSIINSTALLPERUSER=""
```

**Comment by tmontes** [comment]
PROGRESS NOTE:

* Packaged `puppy`.
* Logged in as admin-user and brought up an administrative CLI.
* Installed with `msiexec /i "PuPPY 1.4.0.msi" MSIINSTALLPERUSER=""`.
* Resulting installation is availabable to all users.

NIT-PICK:

* `puppy` was installed onto `C:\Program Files (x86)\PuPPY` which, IIUC, is where 32-bit applications should be installed on 64-bit systems -- AFAICT, PBS is 64-bit so, for the installation to be *correct*, it should have gone into `C:\Program Files\PuPPY`.

NEXT:

* Update docs letting users know how to go about machine-level installs in the current version.
* Log two `LATER` issues:
  * Have machine-level installs go into `C:\Program Files` instead of `C:\Program Files (x86)` (bug).
  * Add `pup` options to produce default-to-machine-level install MSI files (enhancement).

**Comment by tmontes** [comment]
CLOSING after having merged PR #171 updating docs on how to complete per-machine installs with the current `pup`-produced user-installable MSI files.

**Comment by carlosperate** [comment]
Thanks Tiago!
Is there no way to select the option from the installer GUI? Or is that treated as a separate issue?

**Comment by tmontes** [comment]
> Thanks Tiago!
> Is there no way to select the option from the installer GUI? Or is that treated as a separate issue?

Not as of now. Adding a GUI for that option is tracked under #85.
