### ISSUE TITLE
Separate macOS and Windows environmental variables for signing

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/pup#152]
Right now there is a common environmental variable for macOS and Windows, `PUP_SIGNING_IDENTITY`.
For signing via CI we can set it GH Actions to safely save secrets automatically as encrypted env variables from the repository settings, so we would need different names to save the macOS and Windows data.

**Comment by tmontes** [comment]
Hey @carlosperate, giving this some thought, without being aware of the GH Actions details...

I think it is a good idea to have `pup` be as consistent as possible, behaviour-wise, across all the supported packaging scenarios and platforms.

Having differently named env vars, say, on a per-platform basis, clearly goes against that goal.

Won't it be possible to do the equivalent of these shell commands, under GH Actions, instead?

```
# export PUP_SIGNING_IDENTITY=${GH_ACTIONS_VAR_NAME_FOR_THIS_PLATFORM}}
# pup package ...
```

**Comment by carlosperate** [comment]
Yeah, I think in the end I saved the GitHub secrets with a different name and then assigned the env variables depending on platform:
- https://github.com/mu-editor/mu-private/blob/master/.github/workflows/build.yml#L44
- https://github.com/mu-editor/mu-private/blob/master/.github/workflows/build.yml#L51

**Comment by tmontes** [comment]
Oh, great, so that's possible! :)

...so, along with a "striving for cross-environment usage consistency" thought, I'll drop this request, if you agree.

**Comment by carlosperate** [comment]
Sure, it's definitely workable in CI, so it didn't turn out to be a problem.

I guess I didn't expect the same env variable to be used for what could technically be considered two (similar) things, but I see your point as well. For me at least it could be argued either way, and so in that case your way wins ;)
