### ISSUE TITLE
BREAKING: OSX no longer builds because zip file containing wheels doesn't notorize.

### ISSUE THREAD

**Issue by ntoll** [mu-editor/pup#156]
Hi @tmontes,

Just tried to create a release, but I encountered the following error:

```
Notarization failed: 'Package Invalid'. Check log at "https...."
```

I'll email the log file and full details separately. As far as I can tell, now that Mu puts all the wheels into a single zip file, the notorization doesn't work properly (you'll see from the error log I'm going to email you).

As always, please let me know if there's anything I can do to help.

Thanks, N.

**Comment by tmontes** [comment]
@ntoll, inadvertedly closed this but don't want to do it without your confirmation.

Here's my progress:
* PR #157 merged should fix this, signing shared libs within wheels withing ZIP files ad-infinitum.
* `pup` 1.0.0a10 has just been released to PyPI which should be picked up by Mu's CI and hand-driven `make macos`.

Tested it on my system, running macOS 10.14.6: signing and notarization completed ok.

Please let me know of your experience. :)

**Comment by tmontes** [comment]
Closing after confirmation by @ntoll that packaging Mu Editor 1.1.0b5 for macOS is working again.
