### ISSUE TITLE
Linux AppImage | Updates might needed to build an AppImage in a docker container

### ISSUE THREAD

**Issue by carlosperate** [mu-editor/pup#201]
The current progress can be seen in this PR: https://github.com/mu-editor/mu/pull/2218

The current error provided by AppImage in the CI is this:

```
20220510 091829 I pup.plugins.linux.appdir_create appimagetool err: fuse: device not found, try 'modprobe fuse' first
```

Running the steps manually in the same docker container and I get slightly more info:

```
I Step 'linux.appdir_create': starting.
I appimagetool err: fuse: device not found, try 'modprobe fuse' first
I appimagetool out:
I appimagetool out: Cannot mount AppImage, please check your FUSE setup.
I appimagetool out: You might still be able to extract the contents of this AppImage
I appimagetool out: if you run it with the --appimage-extract option.
I appimagetool out: See https://github.com/AppImage/AppImageKit/wiki/FUSE
I appimagetool out: for more information
I appimagetool err: open dir error: No such file or directory
```

The docs indicate that FUSE cannot (safely?) be used in a docker container:
https://docs.appimage.org/user-guide/troubleshooting/fuse.html#fuse-and-docker

The instructions indicate we can can either mount the AppImage, or extract it and run the contents:
https://docs.appimage.org/user-guide/troubleshooting/fuse.html#ref-fuse-fallback

I imagine these additional steps would have to be added to pup if we want to be able to build AppImage in docker containers.

**Comment by tmontes** [comment]
IIUC, the FUSE alternatives apply to using/running previously created AppImages - I was aware of those and tried them before.

In regards to creating AppImages, we might need to go with the "insecure" Docker options (assuming we even can!).

May need further investigation. ;)

**Comment by carlosperate** [comment]
> In regards to creating AppImages, we might need to go with the "insecure" Docker options (assuming we even can!).

We can look into it, but I'd be surprised if we can change the docker configuration in the GitHub actions runners.

Does that mean that without changing the docker flags AppImages cannot be built inside docker containers?
