### ISSUE TITLE
Implement macOS signing and notarization

### ISSUE THREAD

**Issue by tmontes** [mu-editor/pup#43]
PLAN:

* [x] Collect and share documentation links about the topic (many of which I've been reading as of recently).
* [x] Get a developer certificate from Apple.
* [x] Explore the process manually / via ad-hoc scripts, confirming that it seems to work.
* [x] Try to validate it in collaboration with someone else, running macOS Catalina or Big Sur.
* [x] Transpose the process into `pup` code.

NOTE:

* From the investigation so far, it is a very good idea to have a properly layed out, as small as possible macOS Application Bundle to submit for notarization.
* With that in mind, #38 becomes a relevant dependency to this issue's "correct" implementation.

**Comment by tmontes** [comment]
RESOURCES and LINKS:

* [This Mu issue](https://github.com/mu-editor/mu/issues/940), nearly one year old (!!!).
* These articles by @glyph:
  * [Mac Python Distribution Post Updated for Catalina and Notarization](https://glyph.twistedmatrix.com/2019/10/catalina-notarize-python.html)
  * [Tips And Tricks for Shipping a PyGame App on the Mac](https://glyph.twistedmatrix.com/2018/01/shipping-pygame-mac-app.html)
* Apple sourced documents:
  * [WWDC 2019 "All About Notarization" session](https://developer.apple.com/videos/play/wwdc2019/703)
  * [Code Signing Tasks](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html)
  * [Customizing the Notarization Workflow](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow)
  * [Resolving Common Notarization Issues](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/resolving_common_notarization_issues)
* More:
  * [Notarize a Command Line Tool](https://scriptingosx.com/2019/09/notarize-a-command-line-tool/)
  * [How to notarize your software on macOS](https://successfulsoftware.net/2018/11/16/how-to-notarize-your-software-on-macos/)

**Comment by tmontes** [comment]
CONCEPTS (that need better understanding):

* Hardened runtime (and variations thereof?).
* Secure timestamps.
* Entitlements.

**Comment by tmontes** [comment]
WORK IN PROGRESS:

signing script
```
#!/bin/bash
set -e

# Use keychain to allow "codesign" to always access the code signing certificate's private key.

cd ./build/pup > /dev/null 2>&1

BASE_DIR=./mu-editor.app/Contents/Resources/Python/

SIG_ID='<apple signing certificate id -- 10 alphanumeric digits>'
CSOPTS="--deep --force --verify --verbose --sign $SIG_ID --options runtime --timestamp"


# --------------------------------------------------------------------------------
# SIGN all shared libraries

find ${BASE_DIR}/lib -type f -name "*.so" -o -name "*.dylib" | while read SHLIB_TO_SIGN
do
    echo "SIGNING ${SHLIB_TO_SIGN}"
    codesign ${CSOPTS} ${SHLIB_TO_SIGN}
done


# --------------------------------------------------------------------------------
# SIGN binaries

find ${BASE_DIR}/bin -type f | while read BIN_TO_SIGN
do
    echo "SIGNING ${BIN_TO_SIGN}"
    codesign ${CSOPTS} "${BIN_TO_SIGN}"
done


# --------------------------------------------------------------------------------
# SIGN the application bundle itself

echo "SIGNING ./mu-editor.app"
codesign ${CSOPTS} ./mu-editor.app


cd -  > /dev/null 2>&1
```

**Comment by tmontes** [comment]
WORK IN PROGRESS:

notarization request script
```
#!/bin/bash

cd ./build/pup > /dev/null 2>&1


BID='com.github.mu-editor.mu'
USER='<apple-id>'
MUAS='<application-specific-password>'

/usr/bin/ditto -c -k --sequesterRsrc --keepParent ./mu-editor.app/ mu-editor.zip
xcrun altool --notarize-app --primary-bundle-id ${BID} --username ${USER} -p ${MUAS} --file mu-editor.zip  

# will print the Notarization RequestUUID

cd -
```


notarization status script:
```
#!/bin/bash

USER='<apple-id>'
MUAS='<application-specific-password>'

if [ -z "${RID}" ]
then
    echo "Set RID to the Notarization RequestUUID"
    exit
fi

xcrun altool --notarization-info ${RID} -u ${USER} -p ${MUAS}
```

**Comment by tmontes** [comment]
PROGRESS:
* Preliminary scripts created and shared above.
* All scripts work (up to a point).
* Notarization result is unsuccessful:

```
2020-09-17 17:00:21.395 altool[78612:1135309] No errors getting notarization info.

   RequestUUID: ...
          Date: 2020-09-17 15:43:31 +0000
        Status: invalid
    LogFileURL: ...
   Status Code: 2
Status Message: Package Invalid
```

**Comment by glyph** [comment]
Just dropping in here due to the @-mention… (I am so glad that my writing is helping with this, annoying as it is!)

The status message rarely contains enough information to debug notarization failures; you'll really want to look at the log file in that elided `LogFileURL`.

How did you generate the `.zip`?  IIRC "Package Invalid" is an error you can get when forgetting to pass the `-y` option.

**Comment by tmontes** [comment]
@glyph, thanks for chiming in,

Agree and undestand that the actual log holds details that the status cannot convey - the note was posted with brevity and progress sharing/noting in mind. For completeness, it did note that several files were not signed which, somehow, may point at a `.zip` file creation issue (is it including said signatures? I will investigate) which, again, may be somewhat consistent with the "Package Invalid" status...

Wondering what you mean by the `-y` option... The `.zip` file was produced with `/usr/bin/ditto -c -k --sequesterRsrc --keepParent <path-to-app-bundle> <name-of-zip-file>` which, per the man page, does not seem to support such option. Maybe you are refering to the zip command's option, WRT to symlinks?

Regardless of that, again, thanks for your articles and this message. I know I'll have to keep reading, undertanding, exploring, until I have a clear enough mental model of how every bit and piece should fit together: then things should work! :)

**Comment by glyph** [comment]
> Agree and undestand that the actual log holds details that the status cannot convey - the note was posted with brevity and progress sharing/noting in mind. For completeness, it did note that several files were not signed which, somehow, may point at a `.zip` file creation issue (is it including said signatures? I will investigate) which, again, may be somewhat consistent with the "Package Invalid" status...

As I understand it, code signatures are just regular files so they *should* be included with just about any archive creator...

If you're creating binary files with extensions other than `.so` and `.dylib` you might need to modify my simple signing script.  (What files is it complaining about?)

> Wondering what you mean by the `-y` option... The `.zip` file was produced with `/usr/bin/ditto -c -k --sequesterRsrc --keepParent <path-to-app-bundle> <name-of-zip-file>` which, per the man page, does not seem to support such option. Maybe you are refering to the zip command's option, WRT to symlinks?

Ah, yes, sorry I didn't realize that's what `ditto` was doing; I've never used it to create zip archives.  No idea if it has problems with this process!

> Regardless of that, again, thanks for your articles and this message. I know I'll have to keep reading, undertanding, exploring, until I have a clear enough mental model of how every bit and piece should fit together: then things should work! :)

Good luck!

**Comment by tmontes** [comment]
PROGRESS:

* Read a bit more.
* Brought in yet another article on the subject.

THOUGHTS:

* Previous (failed and, admittedly, somewhat rushed) experiences go along with recent readings, boiling down to "probably the signing I've been doing isn't 100% as it should".
* Need to specify entitlements, which I haven't done up until now.
* Want faster iteration cycles:
  * For that I'll create a minimal GUI app, `tkinter`-based.
  * No Qt dependencies (or any other, from PyPI) so smaller in size and with much fewer shared libraries.
  * Should also make it easier to digest any notarization failure reports.

**Comment by tmontes** [comment]
PROGRESS:

* Created minimal GUI app at https://github.com/tmontes/puppy.
* Adjusted hand-hacked scripts:
  * Now signing with entitlements.
  * Now subitting a `.zip` file.
* Notarization is still failing, but now down to a single, common error, once for each of the 9 files that were signed within `puppy.app`. It reads: *"The binary is not signed with a valid Developer ID certificate."*.
* Wonderful. I want my 100 EUR back! :P

**Comment by tmontes** [comment]
PROGRESS (and preliminary SUCCESS!):

* Figured out I had been using the wrong kind of certificate for signing after reading more and with more attention (thanks again to @glyph, who very carefully pinpoints that in his artice).
* Successfully signed, notarized, and stapled `puppy`.
* Will share the binary with the Mu development team to gather feedback.

**Comment by glyph** [comment]
It's been such an inspiration to read this thread, thank you for sharing these updates!

But…

<img width="532" alt="image" src="https://user-images.githubusercontent.com/716529/94069242-17443a80-fda5-11ea-8d5c-02d9b1f9bf87.png">

😢

**Comment by tmontes** [comment]
Wow @glyph, thanks a lot for trying it out! Even though it's a failure, it's the best possible feedback I could have had: an attempt from a completely foreign system, that in no possible way could trust my system.

INVESTIGATED:

* Figured out that the packaged bundle included a soft-link pointing nowhere.
* The output of `spctl --assess --type exec <path-to-app-bundle>` helped pinpointing it.

ALSO:

* Rememberd I have a Catalina VM (I'm packaging on Mojave) which failed as above.

THUS:

* Hand fixed the dangling soft-link, signed, notarized `puppy` again, producing `puppy-1.0.0-macos-post1.zip`.
* Tried out the newly packaged variant on my Catalina VM which ran it with no warnings: looks promising.
* Published it alongside the [previously published release](https://github.com/tmontes/puppy/releases/tag/1.0.0).

**Comment by glyph** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/716529/94099427-c867c680-fddf-11ea-901e-ef1e101c07fd.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/716529/94099448-cf8ed480-fddf-11ea-8ba2-6503a655ecbe.png">
🎉 🎉 🎉

**Comment by glyph** [comment]
An interesting side-note though, which is probably unrelated to code-signing: when I first downloaded it, it unarchived to "puppy 2.app" because of the existing "puppy.app" in my downloads folder.  If the app's name has spaces in it, it fails to launch, due to a buggy shell script.

The shell script is written as:

```sh
#!/bin/sh

exec "$(dirname $0)/../Resources/Python/bin/python3.7" -m puppy "$@"
```

which our trusty ol' friend [ShellCheck](https://www.shellcheck.net) *which you should always be using if you're ever writing a shell script* tells us:

```
In ./Downloads/puppy.app/Contents/MacOS/puppy line 3:
exec "$(dirname $0)/../Resources/Python/bin/python3.7" -m puppy "$@"
                ^-- SC2086: Double quote to prevent globbing and word splitting.

Did you mean:
exec "$(dirname "$0")/../Resources/Python/bin/python3.7" -m puppy "$@"

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

Modifying it in the suggested way fixes the launch, and oddly enough does *not* seem to invalidate the code signature, which seems quite bad; this "main executable" really ought to be covered by the codesigning check; if attackers can rewrite it and it launches anyway then codesigning provides no protection!

However, this strategy of using a shell (or Python or Ruby) "launcher", while a popular trick that worked in the past, seems to be breaking down on more recent macOS releases, particularly catalina.  See [this blog post](https://spin.atomicobject.com/2019/12/12/fixing-emacs-macos-catalina/) about how one Emacs mac build's too-clever binary-selector launching script effectively broke the ability to launch the application multiple times.  `puppy.app` seems to have the same problem - launching it from the Downloads folder while it's open doesn't bring it back to the front.  By contrast, py2app applications use an executable shim and do *not* have this problem, since they don't re-exec; testing with my own pygame apps validates this.  So you might want to figure out some way to build a C executable that invokes Python as a library.

Finally I think using `-m` like this is kind of risky, as it skirts close to the vulnerabilities discussed in https://glyph.twistedmatrix.com/2020/08/never-run-python-in-your-downloads-folder.html.  This won't be a problem for most users given the semantics of app launching, but `-m` seems like a mechanism that is unnecessarily risky for final distribution of a binary artifact.

**Comment by tmontes** [comment]
> An interesting side-note though, which is probably unrelated to code-signing: when I first downloaded it, it unarchived to "puppy 2.app" because of the existing "puppy.app" in my downloads folder. If the app's name has spaces in it, it fails to launch, due to a buggy shell script.
> 
> The shell script is written as:
> 
> ```shell
> #!/bin/sh
> 
> exec "$(dirname $0)/../Resources/Python/bin/python3.7" -m puppy "$@"
> ```
> 
> which our trusty ol' friend [ShellCheck](https://www.shellcheck.net) _which you should always be using if you're ever writing a shell script_ tells us:
> 
> ```
> In ./Downloads/puppy.app/Contents/MacOS/puppy line 3:
> exec "$(dirname $0)/../Resources/Python/bin/python3.7" -m puppy "$@"
>                 ^-- SC2086: Double quote to prevent globbing and word splitting.
> 
> Did you mean:
> exec "$(dirname "$0")/../Resources/Python/bin/python3.7" -m puppy "$@"
> 
> For more information:
>   https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
> ```
> 
> Modifying it in the suggested way fixes the launch, and oddly enough does _not_ seem to invalidate the code signature, which seems quite bad; this "main executable" really ought to be covered by the codesigning check; if attackers can rewrite it and it launches anyway then codesigning provides no protection!

Good catch and thanks for the reference to [ShellCheck](https://www.shellcheck.net) which I didn't know about! Logged #44 to track and improve this.


> However, this strategy of using a shell (or Python or Ruby) "launcher", while a popular trick that worked in the past, seems to be breaking down on more recent macOS releases, particularly catalina. See [this blog post](https://spin.atomicobject.com/2019/12/12/fixing-emacs-macos-catalina/) about how one Emacs mac build's too-clever binary-selector launching script effectively broke the ability to launch the application multiple times. `puppy.app` seems to have the same problem - launching it from the Downloads folder while it's open doesn't bring it back to the front. By contrast, py2app applications use an executable shim and do _not_ have this problem, since they don't re-exec; testing with my own pygame apps validates this. So you might want to figure out some way to build a C executable that invokes Python as a library.

Interesting, and confirmed that mis-behaviour on my Catalina VM. On my dev/packaging system, running Mojave, "relaunching" does bring the running instance's window to the front... That's Catalina changes for us! *sigh* :-)

I wanted to keep things as simple and minimal as possible... But maybe a native executable launcher will be required. Let's see what the future holds. Logged #45 to track this.

Side-side-note: maybe also related to the fact that running the `pup`-packaged `puppy` results in a `python3.7` application name in the menu bar (or, then again, maybe this can be customized from within the app bundle's Info.plist).


> Finally I think using `-m` like this is kind of risky, as it skirts close to the vulnerabilities discussed in https://glyph.twistedmatrix.com/2020/08/never-run-python-in-your-downloads-folder.html. This won't be a problem for most users given the semantics of app launching, but `-m` seems like a mechanism that is unnecessarily risky for final distribution of a binary artifact.

Agreed and, again, thanks for that article which I skimmed before and now read in more detail. :-)

...I guess #42 (partially?) addresses this concern. To learn a bit more, a created (and published `puppy` 1.1.0 that now displays both the CWD and `sys.path`.

What I get on both my Mojave dev/packging system and the Catalina VM differs slightly, but is not very frightening:

* `os.getcwd()`:
  * `/` on both systems, probably due to the way the Python Standalone Build is built.
* `sys.path`:
  * Does include `/` on both systems, again, which is silly and (relatively) safe.
  * Includes no entries outside `.../puppy.app` on Catalina, which looks pretty good.
  * Includes a dangerous entry on my dev/packaging system: `~/.local/lib/python3.7/site-packages`. I suppose this is `site.py` doing its thing and that the local `site-packages` is there (empty, but there) because at some point `pip` may have created it for me.

Again, thanks a lot for your help! :-)

**Comment by glyph** [comment]
> Again, thanks a lot for your help! :-)

Super glad to see folks attacking the problem of proper app distribution with Python, so I'm happy to do so.

**Comment by tmontes** [comment]
Closing:

* Basic, (very) minimal implementation in place.
* Other identified issues created and linked here.
* Let's release and have the team experiment to gather feedback early on.
